- id: gofumpt
  name: gofumpt
  description: Run gofumpt
  entry: gofumpt -w
  types: [go]
  language: golang
  pass_filenames: True
  additional_dependencies: ["mvdan.cc/gofumpt@v0.6.0"]
- id: golines-gofumpt
  name: golines-gofumpt
  description: Run golines with gofumpt as base formatter
  entry: golines -w --base-formatter gofumpt
  args: ["-m120"]
  types: [go]
  language: golang
  pass_filenames: True
  additional_dependencies:
    ["mvdan.cc/gofumpt@v0.5.0", "github.com/segmentio/golines@v0.11.0"]
- id: gci
  name: gci
  description: Control golang package import order and make it always deterministic.
  entry: gci write
  types: [go]
  language: golang
  pass_filenames: True
  additional_dependencies: ["github.com/daixiang0/gci@v0.6.3"]
- id: go-mod-tidy
  name: Run go mod tidy
  entry: ./go-mod-tidy
  files: '\.go$|go.mod$|go.sum$'
  language: script
  args: ["."]
  pass_filenames: false
- id: shfmt
  name: shfmt
  description: Run shfmt to format shell scripts
  entry: shfmt -w
  types: [shell]
  language: golang
  pass_filenames: True
  additional_dependencies: ["mvdan.cc/sh/v3/cmd/shfmt@v3.7.0"]
